# Generated by Django 2.2.4 on 2022-02-19 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fav_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
