# Generated by Django 2.2.4 on 2022-02-19 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fav_app', '0002_auto_20220219_1642'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=55)),
                ('uploaded_by', models.ForeignKey(on_delete='cascade', related_name='books_uploaded', to='fav_app.User')),
                ('users_who_like', models.ManyToManyField(related_name='liked_books', to='fav_app.User')),
            ],
        ),
    ]
